name: ci pipeline
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - run: echo "this is build"

              
      
