name: ci pipeline
on: push
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: read index file
         run: cat index.html

              
      
